### ISSUE TITLE
Pegasus warnings at exit with this theme... what's for?

### ISSUE THREAD

**Issue by fastpop72** [PlayingKarrde/gameOS#109]
I receive always these warnings from Pegasus at exit regarding the theme:

From file GameDetails2.qml line 186:7 i have this error: 

**QML Image: Binding loop detected for property "width"** 

From file ControllerHelp.qml line 16 i have two of this error:

**TypeError: Cannot call method 'name' of undefined**

Is something simple to fix?

Thanks

**Comment by PlayingKarrde** [comment]
Should be fixed on the next big released

**Comment by fastpop72** [comment]
WOW! Can't wait!!!! Thanks!
