### ISSUE TITLE
Crash while navigating down on a list of 600 items

### ISSUE THREAD

**Issue by gcarvalho** [PlayingKarrde/gameOS#110]
I'm running Pegasus with gameOS in a rpi3b.
My arcade list has over 600 items.
Simply pressing down and navigating down causes the display to lock and flicker continuously between two pages. To be fair, pagination is clearly slow and it slmost seems like it trips up on something.
I can still open the menus and even exit Pegasus by remembering the steps, but the display is broken.
On exiting Pegasus I see a bunch of errors on the console refering " framebuffer incomplete attachment".
I know I'm not providing much info, but if you follow this up, feel free to ask me to do any testing.
If not, I'll update as new versions come out and hope it goes away :)

**Comment by gcarvalho** [comment]
Some more experimentation has shown that anythiung over 11 rows of items in the grid causes the crash. Swapping between collections is extremely slow.
I'm going to assume that the rpi3b is simply too slow for this :/

**Comment by PlayingKarrde** [comment]
The new version should work well enough on rpi3b. It will be out in a few days

**Comment by gcarvalho** [comment]
Awesome, waiting with baited breath. Feel free to reach out to me if you need any feedback or testing

**Comment by PlayingKarrde** [comment]
New version is out now.
