### ISSUE TITLE
[Bug] Improve move handling

### ISSUE THREAD

**Issue by iwubcode** [PlayingKarrde/gameOS#113]
When moving (keyboard or gamepad) the movement will sometimes add additional movement?  Example:  moving down one will sometimes move left as well.

Additionally, when moving between the main bar (in game preview) and the media row, hitting down will go down but then bounce back up.  You have to hold down or hit it multiple times for it to take effect.

**Comment by PlayingKarrde** [comment]
Fixed in version 1.0.5

**Comment by iwubcode** [comment]
Awesome.

I just want to say thank you for this theme.  The improvements in 1.0 are **amazing**.  The theme is very beautiful!

**Comment by PlayingKarrde** [comment]
Glad you like it!
