### ISSUE TITLE
[Bug] Gameos "logo" not visible?

### ISSUE THREAD

**Issue by iwubcode** [PlayingKarrde/gameOS#115]
In the youtube preview, there's a very cool "gameOs" logo at start.  However, on mine there is simply a transparent background.  I don't see anything wrong in the log but can provide it if necessary

**Comment by PlayingKarrde** [comment]
Do other videos play ok?

**Comment by iwubcode** [comment]
Most do, although I noticed one video that doesn't (also is transparent).  I was going to look later tonight and see if I can see why.

**Comment by iwubcode** [comment]
Actually feel free to close this, the same bug occurs in Pegasus' main theme.  Must be an issue with codecs or something?

**Comment by PlayingKarrde** [comment]
Are you running on Windows? If so make sure you have k-lite codecs.
