### ISSUE TITLE
how would i make it be able to show boxart when looking at a games bios instead of a wheel?

### ISSUE THREAD

**Issue by ash0903** [PlayingKarrde/gameOS#116]

**Comment by PlayingKarrde** [comment]
Do you mean viewing box art for the list of games? If so I just pushed an update that adds that (in settings under Grid View > Grid Thumbnail (change it to Box Art). 

If you mean on the game details page, there is an option in settings under Game Details > Default to full details.

**Comment by ash0903** [comment]
yes, thats what i was needing thanks!

**Comment by ash0903** [comment]
hey im not sure if you could help me with this ether but Pegasus controls are awful and there mess up game controls. do you know of anyway to fix them?(im using a pi4 btw)
