### ISSUE TITLE
how would i replace the "gameos" previews of games?

### ISSUE THREAD

**Issue by ash0903** [PlayingKarrde/gameOS#118]

**Comment by ash0903** [comment]
how would i replace the "gameos" logo with previews*

**Comment by PlayingKarrde** [comment]
You're going to need to be a bit more specific. Do you mean having games in place of the gameOS starfield on the home screen? If so that is populated by your favourites, so try adding some and they will show up.

**Comment by ash0903** [comment]
oh thank you! i really enjoy the theme!
