### ISSUE TITLE
Stopping the Moonlight retransmission causes the gameOS menu to get stuck

### ISSUE THREAD

**Issue by jraicr** [PlayingKarrde/gameOS#129]
I have moonlight working on Retropie and I'm using gameOS theme on Pegasus. There is a problem when you leave a game using moonlight (stopping the streaming connection with the server) when the stream is closed and get me back to the gameOS interface, I only see a square with a text in the center "Launching Cuphead" in this case. I push back button in the gamepad and I only get the menu to select settings, close, etc and I'm stucked there until I change the Pegasus theme to the original one, then reload gameOS and everything is fine again. 

Any ideas on how to fix this?

**Comment by waldnercharles** [comment]
If you launch the game with the original Pegasus theme does the same issue occur?

If not, posting the `lastrun.log` might help us diagnose the issue better.

**Comment by jraicr** [comment]
This doesn't occur with the original Pegasus theme. The lastrun log can be found [here](https://hastebin.com/joberujixa.sql).

**Comment by PlayingKarrde** [comment]
Fixed with f4c0248
