### ISSUE TITLE
Theme on Linux not working

### ISSUE THREAD

**Issue by LordSchwenk** [PlayingKarrde/gameOS#132]
If i choose the theme in Pegasus on Zorin OS (Ubuntu 18.04 LTS) i get following Errors in the log file. Theme is not running.

`2020-06-27T16:53:47 [w] file:///home/user/.config/pegasus-frontend/themes/gameOS/theme.qml:357:9: Type ShowcaseViewMenu unavailable

2020-06-27T16:53:47 [w] file:///home/user/.config/pegasus-frontend/themes/gameOS/ShowcaseView/ShowcaseViewMenu.qml:6:1: module "QtQml.Models" is not installed

2020-06-27T16:53:49 [i] Closing Pegasus, goodbye!`

**Comment by waldnercharles** [comment]
You might need to install the latest version of Pegasus instead of the stable release.

**Comment by Warfork** [comment]
> If i choose the theme in Pegasus on Zorin OS (Ubuntu 18.04 LTS) i get following Errors in the log file. Theme is not running.
> 
> `2020-06-27T16:53:47 [w] file:///home/user/.config/pegasus-frontend/themes/gameOS/theme.qml:357:9: Type ShowcaseViewMenu unavailable
> 
> 2020-06-27T16:53:47 [w] file:///home/user/.config/pegasus-frontend/themes/gameOS/ShowcaseView/ShowcaseViewMenu.qml:6:1: module "QtQml.Models" is not installed
> 
> 2020-06-27T16:53:49 [i] Closing Pegasus, goodbye!`

https://github.com/mmatyas/pegasus-frontend/releases/tag/continuous

**Comment by PlayingKarrde** [comment]
As waldnercharles stated, you need to run the latest, not stable, release of Pegasus

**Comment by LordSchwenk** [comment]
Thanks. Latest release is not working on my Distro. I'll try to get this working now.

**Comment by sharkisland** [comment]
@PlayingKarrde same bug on Android inside bluestacks, tested with pegasus-fe_alpha13-151-g116e9712_android.apk
