### ISSUE TITLE
[Feature Request] Add a "Completed" tag to games we've finished/beaten

### ISSUE THREAD

**Issue by DrGorillaNuts** [PlayingKarrde/gameOS#139]
Hey all, I suggested this on the Discord and figured I'd submit it here on the Github.  A feature request I'd like to see in the future would be an option to toggle on/off a "Completed"/"Finished"/"100%" option for titles that we've beaten, so we can keep track of finished games in our collections.  This could be done similar to how the Favorite feature works, but maybe have a green "Complete" icon overlay somewhere on the grid picture.

**Comment by PlayingKarrde** [comment]
This is more of a Pegasus level feature request. I can add support for such a feature but it shouldn't really be handled by the theme.
