### ISSUE TITLE
Reduce required QtQuick level

### ISSUE THREAD

**Issue by mmatyas** [PlayingKarrde/gameOS#14]
In QML the QtQuick module's minor version matches the Qt minor version required for running the theme. So when you `import QtQuick 2.11`, the code requires Qt 5.11 and will error if the Qt available is older than that. While Pegasus comes with 5.11 support, building it with older versions is also supported up to Qt 5.9. If the theme does not use QML features added in 5.10-11, you might want to reduce the minor version number for the imports, to .9 or lower.

(This changes only the available properties, not eg. the performance. Actually, for many cases QtQuick 2.0 is usually enough.)

**Comment by PlayingKarrde** [comment]
Thanks. Have moved down to 2.8.
