### ISSUE TITLE
is there anyway to hide emulators? dosbox and amiberry both need there own config to work is there a way to hide them from the menu?

### ISSUE THREAD

**Issue by ash0903** [PlayingKarrde/gameOS#142]

**Comment by PlayingKarrde** [comment]
Is there a reason you don't want to delete their entries from your sources?

**Comment by ash0903** [comment]
some of them are necessary to run an emulator or they'll just be added back in.

**Comment by ash0903** [comment]
also the emulators are case sensitive, so i couldn't make the files case senstive

**Comment by PlayingKarrde** [comment]
I think this is beyond the scope of a theme and should probably be directed at Pegasus instead.
