### ISSUE TITLE
Crashing and other bugs on Android 6

### ISSUE THREAD

**Issue by basvroegop** [PlayingKarrde/gameOS#145]
Hey there!

I just tried running this theme on a device with Android 6 and ran into a few issues. The most prevalent is a consistent crash: the app closes when trying to start a game.

When defaulting to game details, it crashes when clicking on a game when it's supposed to open the details screen. And the shortcut button for details doesn't work, so I'm guessing there's a broader issue there. 

Hoping it's something that can be fixed! I was surprised how smoothly it runs on a relatively underpowered device (I'm using one of these: https://www.goretroid.com/collections/frontpage/products/retroid-pocket-2-handheld-retro-gaming-system). The only other downside seems to be the small font, but considering gameOS is primarily a tv theme that's to be expected.

Thanks!

**Comment by PlayingKarrde** [comment]
I'm afraid I don't have access to any Android 6 devices so won't be able to test, and also don't really have any plans to support it. I'll leave the bug open in case someone else wants to tackle it though.

**Comment by basvroegop** [comment]
Not the same crashes, but different issues pop up. The GPIOS theme crashes when changing tabs, for example. 

If I can help in any way, let me know. And if not: said device should get an update to Android 8.1 in about two months, so it might be worth waiting for that to show up.

**Comment by basvroegop** [comment]
I figured out what's causing these Android-related issues. If you turn off the Android category, they seem to stop happening. Not a perfect solution, because you still need access to those if you want to open apps when Pegasus is acting as a launcher. But it's something to work with!

**Comment by PlayingKarrde** [comment]
Thanks for the update. Hopefully the 8.1 update helps. The system looks quite interesting so I might pick one up for myself to play with in the future.
