### ISSUE TITLE
Box don't show

### ISSUE THREAD

**Issue by Madcore** [PlayingKarrde/gameOS#147]
I scraped everything with Skraper, with the boxes in the "box 2d" folder. But they don't show on the detail view. Instead it shows the game screenshot.

**Comment by PlayingKarrde** [comment]
Do they show on the default theme? Can you post a screenshot and possibly your lastrun.log too?

**Comment by Madcore** [comment]
They didn't show on the default theme. I think I have them in the right folder. "media/box 2d" isn't it?

I have grid view on box art, but it shows wheel logos.

![pegasus-fe_lvl6CJYj2o](https://user-images.githubusercontent.com/1870747/93651173-72bea300-fa08-11ea-8ea7-cd13ae9257c4.png)
![pegasus-fe_J52IETQMiB](https://user-images.githubusercontent.com/1870747/93651175-73efd000-fa08-11ea-9d7f-648fc0de54a9.png)
![pegasus-fe_JdieiwIrLj](https://user-images.githubusercontent.com/1870747/93651177-73efd000-fa08-11ea-9c8c-0b5cfb65aab7.png)

[lastrun.log](https://github.com/PlayingKarrde/gameOS/files/5248524/lastrun.log)

**Comment by PlayingKarrde** [comment]
I think if you're using Skraper.net assets the folder needs to be called "box2dfront"

**Comment by Madcore** [comment]
It worked!
[pegasus-fe_kDMr9ggor5](https://user-images.githubusercontent.com/1870747/93652377-b6b3a700-fa0c-11ea-8b9b-26af44800aa2.png)

I though folder had to be named "box 2d", but it work now. Thanks.
