### ISSUE TITLE
error when run pegasus-fe

### ISSUE THREAD

**Issue by xAzukay** [PlayingKarrde/gameOS#148]
i try to run pegasus-fe on command but show below error
`/opt/retropie/supplementary/pegasus-fe/pegasus-fe: /lib/arm-linux-gnueabihf/libz.so.1: version ZLIB_1.2.9 not found (required by /opt/retropie/supplementary/pegasus-fe/pegasus-fe)
/opt/retropie/supplementary/pegasus-fe/pegasus-fe: /lib/arm-linux-gnueabihf/libm.so.6: version GLIBC_2.27' not found (required by /opt/retropie/supplementary/pegasus-fe/pegasus-fe)
/opt/retropie/supplementary/pegasus-fe/pegasus-fe: /usr/lib/arm-linux-gnueabihf/libssl.so.1.1: version OPENSSL_1_1_1' not found (required by /opt/retropie/supplementary/pegasus-fe/pegasus-fe)
/opt/retropie/supplementary/pegasus-fe/pegasus-fe: /lib/arm-linux-gnueabihf/libc.so.6: version GLIBC_2.28 not found (required by /opt/retropie/supplementary/pegasus-fe/pegasus-fe)
/opt/retropie/supplementary/pegasus-fe/pegasus-fe: /lib/arm-linux-gnueabihf/libc.so.6: version GLIBC_2.25' not found (required by /opt/retropie/supplementary/pegasus-fe/pegasus-fe)`

my retropie install on top of osmc.

**Comment by PlayingKarrde** [comment]
I think this is a pegasus issue rather than a gameOS one. [It would be best for you to direct your question there](https://github.com/mmatyas/pegasus-frontend/issues).
