### ISSUE TITLE
[Bug] Steam platform shows next platform list first time accessed 

### ISSUE THREAD

**Issue by juanma-cvega** [PlayingKarrde/gameOS#152]
I don't know if this is a bug or maybe it's just something in my configuration that doesn't work.
I use LaunchBox as source of data (I haven't configured anything, I had LaunchBox configured and after launching Pegasus games where there already). My list of platforms starts with Steam, followed by Arcade. Every time I start Pegasus, when I try to get into the Steam platform I get the Arcade one. I have to go to Arcade after that and then go back to Steam to see the Steam games.

**Comment by PlayingKarrde** [comment]
Have removed this feature for the time being so Steam won't be ordered first.
