### ISSUE TITLE
Favorites won't save between sessions

### ISSUE THREAD

**Issue by HVR88** [PlayingKarrde/gameOS#169]
If I add any number of favorites, quit Pegasus and re-launch, all favorites are gone.

I have no clue if this is a Theme or Pegasus issue, so I'm posting about it here first.

WIndows 10, gameOS 1.10, Pegasus Feb 19 2021 - Launchbox metadata integration

**Comment by PlayingKarrde** [comment]
This is a Pegasus issue rather than the theme.
