### ISSUE TITLE
What images are used on the home screen?

### ISSUE THREAD

**Issue by DeltaGemini** [PlayingKarrde/gameOS#184]
I have box art displayed in the system screens, but my homescreen only shows the game titles on the tiles. Which images should be displayed here?

**Comment by PlayingKarrde** [comment]
It uses a combination of screenshot, video (if you have it) and game logo

**Comment by DeltaGemini** [comment]
Thanks! It looks like Skraper isn't adding logo to the metadata file, just marquee, video and image. I'll have to find out why.
