### ISSUE TITLE
Video does not play

### ISSUE THREAD

**Issue by ChristofferGreen** [PlayingKarrde/gameOS#50]
Hello, I saw this theme mentioned in r/emulation and liked it so much I decided to set up pegasus (alpha10-16-g0fa980d) and followed instructions for scraping with Skraper. Everything looks good except for the background video behind the game logo/title. After moving to a new game tile the background fades out from the static game image to a grey image, I think it should be fading out to a video as in the example videos of the theme. I have verified that the videos were downloaded to the media/videos dir by Skraper and that they play in the standard windows video player (I am using windows 10).

Are there any requirements, installing a video codec or so that needs to be done?

Thank you.

**Comment by PlayingKarrde** [comment]
Ah yes, you need to install k-lite codec pack if on Windows. There's work being done to move to a new video renderer so this isn't required, but for now this should solve your problem.

**Comment by ChristofferGreen** [comment]
Thank you, that fixed the issue.
