### ISSUE TITLE
Not working on Retropie installed on Debian9 Stretch

### ISSUE THREAD

**Issue by fastpop72** [PlayingKarrde/gameOS#59]
Just trying this theme on pegasus-fe installed through experimental packages of retropie but when i select the theme i have a black screen and everything hangs.

I use retropie installed on PC with Dedian 9 Stretch.

**Comment by PlayingKarrde** [comment]
Do you have both the latest version of this theme as well as the latest beta release of Pegasus? If so can you post your log?

**Comment by fastpop72** [comment]
Thanks for your reply. I managed to get your theme working. Apparently i done nothing wrong, i have two different PC with different hardware but same debian9 installation. One of them your theme works like a charm, the other PC give me a black screen and Pegasus freezes instead. This second PC gives me also an issue with the lr-reicast core emulator and i discovered that all is related to the VGA drivers that debian installs automatically, maybe your theme suffer for the same vga drivers issue in this particular hardware (the hardware is an old Nvidia N68 chipset board with Geforce7050 integrated vga).

Anyway thanks for this theme! That's what i'm looking for!
