### ISSUE TITLE
Improve video loading performance

### ISSUE THREAD

**Issue by waldnercharles** [PlayingKarrde/gameOS#67]
I've noticed that the video loader hangs while loading the Video's QML. I've found a way to fix this here https://github.com/waldnercharles/pegasus-theme-grid-2/blob/master/layer_grid/GameGrid.qml#L71

Unfortunately I decided to implement it from-scratch.

The basic idea is, instead of using a video loader in each GameGridItem, you can use the GameGrid's highlight object.

**Comment by PlayingKarrde** [comment]
Oh great! Thanks for sharing. I will try and implement when I have time.
