### ISSUE TITLE
Video from grid keeps playing when on the game details screen

### ISSUE THREAD

**Issue by spektor56** [PlayingKarrde/gameOS#69]
I set muted = false for the grid screen so i could hear the video audio and noticed it keeps playing when on the game details screen.  If i start the video preview on the game details screen i get double audio playing.

**Comment by spektor56** [comment]
Also, if i lock my screen or leave the app by pressing the home button the audo keeps playing. This also happens on the default theme though.

**Comment by PlayingKarrde** [comment]
The audio playing issue should be directed to the main Pegasus github as that is unfortunately out of my control. I will add a fix for the first issue in the next big update though. Thanks.

**Comment by PlayingKarrde** [comment]
Fixed in 0.6.7 
#94
