### ISSUE TITLE
Setup for skyscraper

### ISSUE THREAD

**Issue by DryKillLogic** [PlayingKarrde/gameOS#78]
Were you able to use skyscraper instead to generate the media?.
I just need to figure out the config for Box2D and Fanart (if possible).

Thanks!

**Comment by PlayingKarrde** [comment]
Unfortunately Skyscraper isn't available on Windows so it is hard for me to test. However I would posit that this is more of a Pegasus issue rather than gameOS as the art should work the same as for the main launcher.

**Comment by PlayingKarrde** [comment]
Going to close this issue as it isn't specific to gameOS

**Comment by DryKillLogic** [comment]
Thanks for your answer Seth. I've contacted Skyscraper's developer, and the changes needed to fetch different asset types are now part of the roadmap.

https://github.com/muldjord/skyscraper/issues/156#issuecomment-537306743
