### ISSUE TITLE
Support multiple backgrounds

### ISSUE THREAD

**Issue by iwubcode** [PlayingKarrde/gameOS#91]
This is a very cool theme!  It'd be nice if multiple backgrounds were specified by a game, you randomly selected one.

**Comment by PlayingKarrde** [comment]
This should be pretty easy to do yes.

**Comment by PlayingKarrde** [comment]
Unfortunately I spoke too soon. Pegasus doesn't currently support multiple backgrounds (it only supports multiple screenshots and videos).

I'm afraid you will have to request this to be added on the Pegasus github before I can implement it on my end (I've done most of the work so it's trivial once that is added into Pegasus).

**Comment by iwubcode** [comment]
Oh really?  Odd, I am able to put multiple values in the background field, so I assumed I could..

**Comment by PlayingKarrde** [comment]
Closing since it is not supported in pegasus

**Comment by iwubcode** [comment]
@PlayingKarrde - see https://github.com/mmatyas/pegasus-frontend/issues/573 , looks like it got implemented!

**Comment by PlayingKarrde** [comment]
I'll add it to the next update
