### ISSUE TITLE
Pressing the back button when in a video preview, works unexpectently

### ISSUE THREAD

**Issue by iwubcode** [PlayingKarrde/gameOS#96]
When pressing the back button while watching a video preview, you get taken back to the game-list instead of the game page itself.  Not sure if intentional but it seemed a little odd to me (I know I could press 'accept' to go back with the button...)

**Comment by PlayingKarrde** [comment]
Yes wasn't intentional and I kept meaning to make an issue for it but also forgetting, so thanks for the reminder.

**Comment by iwubcode** [comment]
No problem.  Thank you @PlayingKarrde for such a wonderful theme!!

**Comment by PlayingKarrde** [comment]
Fixed #101
