### ISSUE TITLE
Hide the title text when a video executes on the main selection screen

### ISSUE THREAD

**Issue by iwubcode** [PlayingKarrde/gameOS#99]
This is a style thing, so very subjective, but I think it'd be nicer to hide the title text (fade?) when the video preview executes on the selection screen.  The selection title is below, so I'm not sure if needs to be in both places.

**Comment by PlayingKarrde** [comment]
Do you mean the game logo? If so I'll have to think on that. I could maybe add the code but comment it out if you want to make that change locally (I feel like it's too granular of a change to be used in theme options)

**Comment by iwubcode** [comment]
> Do you mean the game logo?

Ah!  I don't have any game logos, so I'm guessing I see text instead.  Honestly, thinking about this more, I'd say feel free to close this.  I realized I'm probably being a bit too nitpicky for this one.  Sorry!

**Comment by PlayingKarrde** [comment]
No actually you do bring up a good point. If it's text only (this is meant as a fall back only if there are no logos so I haven't spent a long time making this scenario look good) I could see this being redundant information. I'll look into making this situation look a bit better.

Do you mind me asking why you don't use logos?

**Comment by iwubcode** [comment]
> Do you mind me asking why you don't use logos?

Not at all.

The short answer is that I haven't given it a fair attempt (I've only looked up a few of the logos for games).

The longer answer is that I'm kinda picky about my content and I tend to prefer 'official' stuff over fan-made stuff (I use release trailers for all my videos for instance).  For a number of the games I have the logos seem to have had some artistic interpretation and I just didn't like them.

**Comment by PlayingKarrde** [comment]
Interesting. In my experience all the scraped logos have been official logos, but to each their own.

**Comment by iwubcode** [comment]
Now you have me curious.  Maybe today I'll go grab the logos for all my games...

**Comment by PlayingKarrde** [comment]
Fixed #101

**Comment by barolo** [comment]
> Fixed #101
@PlayingKarrde 
Circling back on this, I'd really love to have option to fade out logos when thumbnail playing executes or when it's selected. It feels weird/wastefull to have it animate, when in case of the FHD screen 50% of it is covered, in the middle too, where action is focused most of the time
